app:
  name: "Amis Portal"

server:
  host: "amis-portal.onrender.com"
  port: "8080"

db:
  username: amis
  password: qaibOry3utzA0aZnyh7pYU36apWGqpIp
  host: "amis-portal.onrender.com"
  port: 5432
  postgresport: 9920 
  pusername: amis
  name: amis_db
